name: Lint docs

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Enable corepack
        run: |
          mkdir -p $HOME/bin
          export PATH=$HOME/bin:$PATH
          echo "$HOME/bin" >> $GITHUB_PATH
          corepack enable --install-directory $HOME/bin
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
      - name: Install dependencies
        run: yarn install --immutable
      - name: prettier
        run: yarn lint
